export const FUN_FACTS = [
  "The average person speaks around 16,000 words per day.",
  "Humans can detect a smile in someone's voice without seeing their face.",
  "In Japanese business culture, silence is considered a form of respect.",
  "The word 'salary' comes from the Latin 'salarium' — payment in salt.",
  "Eye contact during speaking increases perceived credibility by up to 43%.",
  "Over 80% of communication is non-verbal — but voice tone alone accounts for 38%.",
  "The most effective speakers use pauses, not filler words, for emphasis.",
  "Speaking at 130–150 words per minute is considered the ideal pace for clarity.",
  "The fear of public speaking affects up to 75% of the population.",
  "Churchill, Lincoln, and Obama all practiced speeches aloud for hours before delivery.",
  "Using someone's name in conversation increases their trust in you by 30%.",
  "The human brain processes speech three times faster than it can read text.",
  "The word 'communicate' derives from the Latin 'communicare' — to share.",
  "Confident speakers tend to end sentences with falling intonation, not rising.",
  "Research shows storytelling activates 5 areas of the brain simultaneously.",
  "'Um' and 'uh' are linguistically functional — they signal the brain is still speaking.",
  "Steve Jobs rehearsed every keynote presentation for hundreds of hours.",
  "The average attention span during a meeting drops by half after 30 minutes.",
  "A strong opening statement is remembered 70% more than the content that follows.",
  "Mirroring someone's speaking pace creates an unconscious sense of trust.",
  "Pausing for one full second after a key point makes it 50% more memorable.",
  "Multilingual speakers often have stronger executive function in their primary work language.",
  "The first 7 seconds of a meeting set the perceived authority of the speaker.",
  "Lowering your pitch at the end of a sentence signals certainty and competence.",
  "Most CEOs spend 70% of their workday in spoken communication.",
];

export const randomFact = () => FUN_FACTS[Math.floor(Math.random() * FUN_FACTS.length)];
